### ISSUE TITLE
rgrl_estimator test fails periodically.

### ISSUE THREAD

**Issue by hjmjohnson** [vxl/vxl#96] opened 2016-01-08 22:13 UTC
There is likely an uninitialized variable.

for i in $(seq 1 30); do ctest -R rgrl_estimator; done

The test failed 2 out of 30 times, and passed 28 out of 30 times.

This was on a linux computer.

Hans

**Comment by hjmjohnson** [comment] 2016-01-12 15:05
@yanggehua Here is the issues to track and comment on fixing this problem.

When you write your comment for the patch set that fixes this, please include "resolves #96" so that this issues is automatically closed and linked to the fix.

**Comment by yanggehua** [comment] 2016-01-12 15:22
@hjmjohnson  Thanks for the information.   I was looking at the VXL dashboard but cannot find a failure of rgrl_estimator.  Could  you please kindly point me to one of such failures?

**Comment by hjmjohnson** [comment] 2016-01-12 17:06
@yanggehua 
** The test failed 2 out of 30 times, and passed 28 out of 30 times. **

for i in $(seq 1 30); do ctest -R rgrl_estimator; done

It either segmentation faults, or times out for failures.  It appears that a variable is not being explicitly set to a known value (probably 0).  When it is "accidently" set to zero, then the test passes.

Hans

**Comment by yanggehua** [comment] 2016-01-25 15:28
Hmmm... I cannot re-produce this issue.  I tried on two computers, Windows 10 and OpenSuse 13.2 64-bit.  I tried both 32-bit and 64-bit, debug and release on the latter.  I even increase the count to 100 times of the loop.  Still, I did not have any single failures.

**Comment by hjmjohnson** [comment] 2016-02-06 19:36
@yanggehua I don't know how to force it to fail, but it often fails on the travis testing environment.  See again pull request failure #160

**Comment by yanggehua** [comment] 2016-02-10 15:50
@hjmjohnson I will take a look a little later. The problem is that the test uses random number generator.  I cannot reproduce this failure on my computer and this travis build does not provide any detailed information.

**Comment by hjmjohnson** [comment] 2016-02-10 16:10
Thanks Gehua,

I know these problems are difficult.  Let’s not discount the fact that perhaps the test itself is a bad test, and the underlying algorithm may be OK.

My gut feeling is that this is due to uninitialized variables being used.  You may want to look at the identified more errors: https://open.cdash.org/viewDynamicAnalysis.php?buildid=4229188  and determine if any of these reported problems are related to features used by this test.



Hans

**Comment by yanggehua** [comment] 2016-02-10 19:46
@hjmjohnson Thanks for the suggestion.  After taking a look, however, none of the issues reported are related to test_estimator.cxx or the files used by this test.   

I looked through builds on the dashboard and found one failure on  CentOS6Linux-gcc-4.4.7-Release-shared (urras.kitware), https://open.cdash.org/testDetails.php?test=417952803&build=4225414.  I have committed fix and will see how it works.   

In both cases, this new one and the old one I found,  it was using random number generator to generate point location or add perturbation to the initial estimate.  I reduced the multiplier on the random number.

**Comment by decrispell** [comment] 2016-02-10 20:18
You could always seed the random number generator with a hard-coded constant for easier repeatability.  Of course if there really is a bug that is only exposed by just the right combination of random values you might not ever see it again.

**Comment by yanggehua** [comment] 2016-02-10 20:31
Let's see if it is getting any better (or not).

**Comment by mleotta** [comment] 2016-02-10 20:39
I’ve seen the debate before about whether or not to seed random number generators in unit tests with fixed constants.  In the past the conclusion has been that generally you should do this.  At the end of the day, repeatability is most important in these unit tests so that it is easier to debug.  We want tests to fail when someone breaks the code, not at random due to random number selection.  If the test result can change from day to day depending on the random sample, it becomes less useful.

**Comment by yanggehua** [comment] 2016-02-10 20:47
@mleotta A point well made.   If the test fails again, I will take this approach, using a fixed seed for random number generator.

**Comment by yanggehua** [comment] 2016-02-23 16:34
A fixed random seed is now used for the test in question.

**Closed by yanggehua** 2016-02-23 16:34 UTC
