### ISSUE TITLE
 The C++ Standard Library forbids macroizing keywords. Enable warning C4005 to find the forbidden macro.

### ISSUE THREAD

**Issue by zahidmak** [vxl/vxl#402] opened 2017-07-05 22:10 UTC
I am getting following two error while compiling vxl-1.14.0 in Visual Studio 2015 Enterprise.

Do you know what is causing this error and what can I do to prevent it. Thanks in advance.

```
#error:  The C++ Standard Library forbids macroizing keywords. Enable warning C4005 to find the forbidden macro.	vnl	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xkeycheck.h	250
```
	
Thank you,
Zahid

**Comment by hjmjohnson** [comment] 2018-01-15 16:02
Zahid,  Can you provide a merge request that fixes this problem?  I do not have access to that compiler and cannot reproduce your problem.

I'm closing this issue for now.  If you provide a Merge request, we can reopen and address this.

**Closed by hjmjohnson** 2018-01-15 16:02 UTC
