### ISSUE TITLE
linker in Mac 10.14.2

### ISSUE THREAD

**Issue by lood339** [vxl/vxl#571] opened 2019-01-06 02:06 UTC
There is a message "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../lib/libvil_io.a(vil_io_smart_ptr+vil_image_view_base-.cxx.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../lib/libvil_io.a(vil_io_smart_ptr+vil_image_view_base-.cxx.o) has no symbols["
As a result, vil_load causes a linker error.
It is tested on Mac 10.14.2 with Xcode 10.1

**Comment by lood339** [comment] 2019-01-12 14:07
After some other tries, I turn off the vil library and only use vnl, vpgl, ...
CMAKE_DEPENDENT_OPTION( VXL_BUILD_CORE_IMAGING "Build VXL's imaging libraries" OFF "NOT VXL_BUILD_CORE_NUMERICS_ONLY" ON)

**Comment by hjmjohnson** [comment] 2019-01-12 14:11
@lood339 Can you please provide your exact command lines used to trigger this situation.

I can not reproduce this problem.   The "has no symbols"  is not an error, it is a warning.   I do not see the linker error.

**Comment by lood339** [comment] 2019-01-14 05:56
@hjmjohnson In my case, I update the mac os from 10.9 to 10.14. As a result, the system (related /usr/bin/ranlib) has some unknown problem. When compile vxl, it is a warning and I can still get the vil_io library. When the library is used in a xcode project, the project reports a linker error with vil_load. To solve this problem, I reinstall the Mac OS and turn off vil and vil_io. So I think the original linker problem is caused by the Mac OS not vxl itself.

**Comment by hjmjohnson** [comment] 2019-01-14 14:10
"So I think the original linker problem is caused by the Mac OS not vxl itself."

@lood339 Thank you for the followup.  I'm closing this issue.  If you find that the problem is due to VXL, please make a pull request and we will  review and incorporate.

**Closed by hjmjohnson** 2019-01-14 14:10 UTC
