### ISSUE TITLE
Please add -msse2 on i386 architectures

### ISSUE THREAD

**Issue by yurivict** [vxl/vxl#795] opened 2020-09-24 20:40 UTC
vxl depends on SSE2 but it isn't enabled by default on i386.
See the failure log: http://beefy10.nyi.freebsd.org/data/113i386-default/549877/logs/vxl-2.0.2.629.log

**Comment by yurivict** [comment] 2020-09-24 20:56
Actually, this should be done in the ITK project.

https://github.com/InsightSoftwareConsortium/ITK/issues/2011

**Comment by hjmjohnson** [comment] 2020-09-24 21:44
Is this a duplicate of #761 ?

**Comment by yurivict** [comment] 2020-09-24 21:57
I think so, this is because it has never been fixed.

**Closed** 2020-09-24 22:01 UTC
